# 02-buildconfig.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: websocket-webapp
  namespace: test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: websocket-webapp:latest
  source:
    type: Git
    git:
      uri: https://github.com/valerio-muredda/tcpsocket.git
      ref: main # e.g., main
    contextDir: ocstuff # e.g., /websocket-app
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile # If Dockerfile is not in the contextDir root
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
